function [fitresult, gof] = createFit_LongRangeIR(Position, Analog, weights)
%CREATEFIT(POSITION_REDUCED_RANGE,ANALOG_AVG_REDUCED_RANGE,WEIGHTS_REDUCED_RANGE)
%  Create a fit.
%
%  Data for 'LongRangeIR_reduced_range' fit:
%      X Input : Position_reduced_range
%      Y Output: Analog_avg_reduced_range
%      Weights : weights_reduced_range
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-May-2015 17:44:51


%% Fit: 'LongRangeIR_reduced_range'.
[xData, yData, weights] = prepareCurveData( Position, Analog, weights );

% Set up fittype and options.
ft = fittype( 'A*(1/x)^b', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.157613081677548 0.902901806559789];
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

coeffs = coeffvalues(fitresult);

% Plot fit with data.
figure( 'Name', 'Long Range IR' );
h = plot( fitresult, xData, yData);
legend( h, 'experiment', ['fit, y = ' num2str(coeffs(1)) '*(1/x)^' num2str(coeffs(2))], 'Location', 'NorthEast' );
% Label axes
xlabel('Position [cm]','FontSize',28)
ylabel('Arduino analog signal','FontSize',28)
ax = gca; % handle of current axes
ax.FontSize = 28;

grid on


