function [fitresult, gof] = createFit_LongRangeIR_analog2dist(Analog_avg, Position, weights)
%CREATEFIT(ANALOG_AVG,POSITION,WEIGHTS)
%  Create a fit.
%
%  Data for 'untitled fit 3' fit:
%      X Input : Analog_avg
%      Y Output: Position
%      Weights : weights
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-May-2015 18:57:44


%% Fit: 'untitled fit 3'.
[xData, yData, weights_1] = prepareCurveData( Analog_avg, Position, weights );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [5798.65973734101 -1.02280985554997];
opts.Weights = weights_1;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

coeffs = coeffvalues(fitresult);

% Plot fit with data.
figure( 'Name', 'Long Range IR' );
h = plot( fitresult, xData, yData);
legend( h, 'experiment', ['fit, y = ' num2str(coeffs(1)) '*x^{' num2str(coeffs(2)) '}, R^2 = ' num2str(gof.rsquare)], 'Location', 'NorthEast' );
% Label axes
ylabel('Position [cm]','FontSize',28)
xlabel('Arduino analog signal','FontSize',28)
ax = gca; % handle of current axes
ax.FontSize = 28;



% % Plot fit with data.
% figure( 'Name', 'untitled fit 3' );
% h = plot( fitresult, xData, yData );
% legend( h, 'Position vs. Analog_avg with weights', 'untitled fit 3', 'Location', 'NorthEast' );
% % Label axes
% xlabel Analog_avg
% ylabel Position
grid on


